In [11]:
import matplotlib.pyplot as plt 
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
X = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [13]:
model = LogisticRegression(solver='liblinear', random_state=42)

In [14]:
model.fit(X, y)

LogisticRegression(random_state=42, solver='liblinear')

In [15]:
model.classes_

array([0, 1])

In [16]:
model.predict_proba(X)

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [17]:
model.score(X, y)

0.9

In [18]:
confusion_matrix(y, model.predict(X))

array([[3, 1],
       [0, 6]], dtype=int64)

In [20]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10

